export const arrayProblems = [
  {
    title: "Two Sum",
    topic: "Arrays",
    difficulty: "Easy",
    platform: "LeetCode",
    link: "https://leetcode.com/problems/two-sum/",
    quizTag: "array_hashing",
  },
  {
    title: "Best Time to Buy and Sell Stock",
    topic: "Arrays",
    difficulty: "Easy",
    platform: "LeetCode",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    quizTag: "array_greedy",
  },
  {
    title: "Contains Duplicate",
    topic: "Arrays",
    difficulty: "Easy",
    platform: "LeetCode",
    link: "https://leetcode.com/problems/contains-duplicate/",
    quizTag: "array_hashing",
  },
  {
    title: "Subarray Sum Equals K",
    topic: "Arrays",
    difficulty: "Medium",
    platform: "LeetCode",
    link: "https://leetcode.com/problems/subarray-sum-equals-k/",
    quizTag: "prefix_sum",
  },
  {
    title: "Maximum Subarray",
    topic: "Arrays",
    difficulty: "Medium",
    platform: "LeetCode",
    link: "https://leetcode.com/problems/maximum-subarray/",
    quizTag: "kadane",
  },
];
